global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'daemon'
    static_configs:
      - targets: ['daemon:8080']
