name: Build and push csm-prover-tool to dev

run-name: Build and push csm-prover-tool:dev to dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  build-and-push:
    uses: lidofinance/actions/.github/workflows/k8s-build-push-harbor.yml@c7b5b6c5d8013046347d728d748fa741eb214e28
    with:
      tag: dev
      registry: registry.dev.k8s-dev.org
      registry_username: ${{ vars.REGISTRY_USERNAME }}
      image: team-csm/csm-prover-tool
      environment: harbor_dev_release
    secrets:
      registry_token: ${{ secrets.HARBOR_DEV_TOKEN }}
